name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "af7878bd7d2d4c90a9fa913fd71c28e3", preview_id = "af7878bd7d2d4c90a9fa913fd71c28e3" }
]
